### ISSUE TITLE
Callbacks from parent ViewComponent are not called

### ISSUE THREAD

**Issue by stefan-schindler** [joshleblanc/view_component_reflex#102]
Hi, we have base view component class, from which all our view components inherit. It defines a `before_reflex` callback:
```ruby 
class BaseComponent < ViewComponentReflex::Component
  before_reflex do
    puts 'Base before_reflex'
  end
end
```
Then in an actual `TableComponent` which inherits from the `BaseComponent`, we have another `before_reflex` callback and  we have defined a `next_page` reflex method:
```ruby
class TableComponent < BaseComponent  
  before_reflex do
    puts 'Child before_reflex'
  end
  
  def initialize()
    @page = 0
  end

  def next_page()
    @page += 1
  end
end
```

And the problem is, that when the `next_page` reflex is called on a button click, only the child `before_reflex` is called and the console contains only this output:
```
Child before_reflex
```
However I would expect, that both callbacks would be called. 

Is the way it works now (only child callback executed) desired, or is this some kind of a bug? 

PS: If I remove the child's `before_reflex` callback, the parent's callback is still not called, so it is not a problem of owerwriting.

Thanks

**Comment by joshleblanc** [comment]
What version are you running?

I'll take a look, see what I can see

**Comment by stefan-schindler** [comment]
We are using the latest 3.3.0 version.
Thanks :)

**Comment by joshleblanc** [comment]
@stefan-schindler Give 3.3.1 a try

**Comment by stefan-schindler** [comment]
Thank you very much for such quick fix, it works now!🙂
