### ISSUE TITLE
Lifecycle Callbacks?

### ISSUE THREAD

**Issue by suan** [joshleblanc/view_component_reflex#13]
Is there any way to set before_reflex etc type callbacks in my `ViewComponentReflex::Component`? It's been extremely painful without this capability.

Looking further, I think one root cause is that the library inherits off of `StimulusReflex::Reflex`, whereas many codebases use the base `ApplicationReflex` pattern... if one could configure a base reflex class, that would be helpful too

**Comment by joshleblanc** [comment]
Lifecycle methods should now work.

You can now specify the reflex base class with `reflex_base_class(new_class)` in your component.
