### ISSUE TITLE
CableReady detected an error in morph!

### ISSUE THREAD

**Issue by gordienko** [joshleblanc/view_component_reflex#17]
I managed to launch my StimulusReflex application on IE11, but I can’t start the component, I get the error: CableReady detected an error in morph! Failed to get the "nodeType" property of a link whose value is undefined or is NULL.

How can you fix this?

**Comment by joshleblanc** [comment]
SR doesn't support IE11 as of yet, but this PR should be what you're looking for: https://github.com/hopsoft/stimulus_reflex/pull/345
