### ISSUE TITLE
Update a model in an easy way?

### ISSUE THREAD

**Issue by emilkarl** [joshleblanc/view_component_reflex#20]
Is there a best practice for handling model updates with ViewComponentReflex?

Im trying to do something like this but when the action `toggle` is reflexed the `@todo` is a hash and not a model. How would you handle a case like this? 

```ruby
# components/todo_component.rb
class TodoComponent < ViewComponentReflex::Component
  def initialize(todo:)
    @todo = todo
  end

  def collection_key
    @todo.id
  end

  def toggle
    @todo.update_attributes(completed_at: @todo.completed? ? nil : Time.current)
  end
end

# components/todo_component.html.erb
<%= component_controller do %>
  <%= @todo.title %>
  <%= @todo.completed? %>
  <%= reflex_tag :toggle, :button, "Toggle" %>
<% end %> 


# todos/index.html
<%= render(TodoComponent.with_collection(Todo.all)) %>
```

This is the solution I can come up with...not sure if its the best one? 🤷‍♂️

```ruby
def toggle
  @todo = Todo.find(@todo["id"])
  @todo.update_attributes(completed_at: @todo.completed? ? nil : Time.current)
end
```

**Comment by joshleblanc** [comment]
That shouldn't be the case, I modify models directly throughout the expo.

https://github.com/joshleblanc/view_component_reflex_expo/blob/master/app/components/todo_component.rb

Do you have a repo I can look at that reproduces the issue?

**Comment by emilkarl** [comment]
Wow, ok that looks nicer. I dont but Im using Rails 5.2? Do I need Rails 6 for this to work properly? 

I can try a reproduce in a separate project maybe.

**Comment by joshleblanc** [comment]
Hi, try the latest version, the rails version requirement was relaxed.

**Comment by emilkarl** [comment]
I think it had to do with our SessionStore. Found some other issues with Rails 5.2 tho. Will put up a PR .
