### ISSUE TITLE
Anycable problem solved

### ISSUE THREAD

**Issue by sebyx07** [joshleblanc/view_component_reflex#23]
Leaving this, might help others:

I tried this with any cable and I had to add this to `development.rb`
Otherwise @instance_variables were `nil` after a reflex

```ruby
  config.cache_store = :redis_cache_store, { url: "redis://localhost:6379/1", driver: :hiredis }
  config.session_store :cache_store
```

**Comment by joshleblanc** [comment]
I added this to the readme
