### ISSUE TITLE
Nested controller in folders: separator different from stimulus reflex original lib

### ISSUE THREAD

**Issue by jonatassalgado** [joshleblanc/view_component_reflex#26]
Some reason to use  "/" and not "--" as separator? Like in stimulus reflex lib https://github.com/stimulusjs/stimulus/pull/65

When we use some like:

- components
  - example_folder
    - example_component.html.erb
    - example_component.rb -> ExampleFolder::ExampleComponent
    - example_controller.js

The controller generated is: `example-folder/example` and not `example-folder--example`

**Comment by cj** [comment]
@jonatassalgado I just ran into this issue myself, great minds!

**Comment by joshleblanc** [comment]
Sorry for the delay, just finally catching up on my free time!

This should be fixed in 3.0.4
