### ISSUE TITLE
Error when booting rails server in Rails 6.1.0.alpha

### ISSUE THREAD

**Issue by sneveu** [joshleblanc/view_component_reflex#28]
Immediately after installing the gem, when trying to fire up the rails server in Rails 6.1.0.alpha, I get the following error message.

```.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/rails-2042865c5f46/activesupport/lib/active_support/core_ext/module/attribute_accessors.rb:52:in `mattr_reader': module attributes should be defined directly on class, not singleton (TypeError)```

Is there support for Rails 6.1.0 yet?

**Comment by sneveu** [comment]
We were able to monkey patch the above issue but then ran into the following error when invoking a reflex action taken from the docs which suggests it's incompatibility with Rails 6.1.

```↓ reflex ↓ CounterComponent#increment StimulusReflex::Channel Failed to invoke CounterComponent#increment! http://localhost:3000/ undefined method `render_component_to_string' for #<WelcomeController:0x0000000000d688>
Did you mean?  render_to_string .../.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/view_component_reflex-2.6.0/lib/view_component_reflex/reflex.rb:43:in `refresh_component!'```

Am I missing something? If not, is support for 6.1 in the roadmap at all?

**Comment by joshleblanc** [comment]
`render_component_to_string` is from view_component https://github.com/github/view_component/blob/master/lib/view_component/render_component_to_string_helper.rb

I'll update the expo to 6.1 shortly and work through the issues it brings up.
