### ISSUE TITLE
Error generating Reflex classes in Rails 5.2

### ISSUE THREAD

**Issue by emilkarl** [joshleblanc/view_component_reflex#30]
Found a possible issue with this in Rails 5.2. Seems like `module_parent` is introduced in [Rails 6](https://apidock.com/rails/v6.0.0/Module/module_parent). If someone could look in to it, it would be nice. I can take a look and create a PR but not at the moment. 

Getting this error: 

![image](https://user-images.githubusercontent.com/10711/97907689-efea7100-1d45-11eb-9eb0-17d212d1beaf.png)

Error is traced down to 

https://github.com/joshleblanc/view_component_reflex/blob/c01494d543f6c621b3a1445833b86e65b0fdb434/lib/view_component_reflex/engine.rb#L22

and

https://github.com/joshleblanc/view_component_reflex/blob/a69373cd60731ece78b76798638513777039dea3/lib/view_component_reflex/reflex_factory.rb#L37-L44

Refs #19

**Comment by joshleblanc** [comment]
Looks like we can use `parent` instead of `module_parent` in rails < 6, but I'll have to test it. 

Thanks for the report
