### ISSUE TITLE
Saving state on refresh includes omitted state

### ISSUE THREAD

**Issue by stevegeek** [joshleblanc/view_component_reflex#37]
Hi!

I think 

https://github.com/joshleblanc/view_component_reflex/blob/3a588334cc15e993871fc5ba149617f36e1f9c33/app/components/view_component_reflex/component.rb#L188 

should be taking into account `omitted_from_state`

ie fix is:
```ruby 
    def safe_instance_variables
      instance_variables - unsafe_instance_variables - omitted_from_state
    end
 
...

    def create_safe_state
      safe_instance_variables.each_with_object({}) { |k, a| a[k] = instance_variable_get(k) }
    end
```

cause in 

https://github.com/joshleblanc/view_component_reflex/blob/3a588334cc15e993871fc5ba149617f36e1f9c33/lib/view_component_reflex/reflex.rb#L144

the omitted state is not correctly removed otherwise

**Comment by joshleblanc** [comment]
They're omitted on line 206, but omitting directly in safe_instance_variables is more readable. If you want to submit a PR for this, I'll accept it.

**Comment by stevegeek** [comment]
Ok sure! Yeah they are omitted on 206 in Component but not in Reflex where the problem is fundamentally
