### ISSUE TITLE
Auto-loading reflex base class in development

### ISSUE THREAD

**Issue by joseph1wan** [joshleblanc/view_component_reflex#38]
Really two issues here. Let me know if you want this split into two issues:

### 1. The `reflex_base_class` does not get passed on with inheritance
Given:

```
class BaseComponent < ViewComponentReflex::Component
  reflex_base_class ApplicationReflex
end
```

Any class inheriting from `BaseComponent`, such as `CustomComponent < BaseComponent` does not have access to the `reflex_base_class` and has to explicitly declare `reflex_base_class ApplicationReflex`

### 2. Changes to the class defined in `reflex_base_class` don't auto-load
I verified that the class defined by `reflex_base_class` does auto-load, but the changes do not propagate to components using that class on browser refresh. The changes only propagate when I restart the server.

Thanks!

**Comment by joshleblanc** [comment]
3.0.0 Should fix both of these issues. 

Not that the breaking change here is `reflex_base_class` is now an accessor rather than a method.

**Comment by joseph1wan** [comment]
Thanks!
