### ISSUE TITLE
uninitialized constant Reflex when using component_controller

### ISSUE THREAD

**Issue by danclark5** [joshleblanc/view_component_reflex#4]
I'm attempting to integrate this gem into my own project, but I'm getting

```
ActionView::Template::Error (uninitialized constant Reflex):                              
    2:                                                                              
    3: <%= render 'form', ingredient: @ingredient %>                         
    4:                                                                        
    5: <%= render(CounterComponent.new) %>                                       
    6: <%# render(IngredientSelectComponent.new(data: {reflex: "change->IngredientSelectComponent#update_select_options"})) %>
    7:                                                                                                                                  
    8: <%= link_to 'Show', @ingredient %> |                   
```
Ignore the IngredientSelectComponent. I tried to get a baseline by copy/pasting your CounterComponent example out of the expo project.

I saw that you called out something similar in the README, but [I am wrapping the `CounterComponent` component with `component_controller`](https://github.com/danclark5/dindin/blob/view-component-reflex/app/components/counter_component.html.erb). I did find that if add a require to the top of [component.rb](https://github.com/joshleblanc/view_component_reflex/blob/master/app/components/view_component_reflex/component.rb) like this
```
require_relative '../../reflexes/view_component_reflex/reflex.rb'
```
I got farther but I think I am doing something wrong. Also things were still breaking just differently. Any thoughts?

**Comment by danclark5** [comment]
After tinkering around with this a bit. I'm realizing this is a rails engine, but I'm not sure why my app isn't loading the reflex in. It might be me not understanding rails engines.

Anyway, I can get past that error message if a fully qualify the references to Reflex [like this](https://github.com/danclark5/view_component_reflex/commit/38c54ec1703278b2d228b5e9a004dff90af68371). I still have issues but I have to look into them later.

**Comment by joshleblanc** [comment]
Hi @danclark5,

Can you try installing the gems `view_component_reflex@2.1.1`, `stimulus_reflex@3.3.0.pre2`, and the yarn package `stimulus_reflex@3.3.0-pre2`, and let me know if it works for you?

Thanks

**Comment by danclark5** [comment]
I updated the three and I'm still getting `uninitialized constant Reflex`. If I'm understanding engines correctly these should just be recognized.

**Comment by danclark5** [comment]
Taking a step back. What do I need to do to get this up in running in a new application? Do I need to install stimulus reflex? These might not be obvious questions, and the applicable answers should probably be in the README.

Here's what I'm trying after `rails new`
- Add `gem 'view_component_reflex'` to the Gemfile and run `bundle`.
- Add `require "view_component/engine"` right after `require 'rails/all'`.
- `mkdir` the components directory under app.
- copy/paste `counter_component.rb` and `counter_component.html.erb` from view_component_expo
- created a pages controller and plopped the component in with a simple `<%= render(CounterComponent.new) %>`

With that I got `uninitialized constant #<Class:0x00007faeb0025290>::CounterComponent`, so I'm definitely missing things. I'm not sure why it's messing up with CounterComponent, but that might be because I haven't installed stimulusreflex yet. I'll try that Thursday morning. I put this recent attempt at https://github.com/danclark5/view_component_reflex_expo. Note the components and the pages controller and test view.

**Comment by joshleblanc** [comment]
That's intersting. I cloned your project and tested it with 2.1.2, and it was working.

I'll take a look in a minute

**Comment by joshleblanc** [comment]
Oops, sorry. That should have been view_component_reflex@2.1.2, not 2.1.1

**Comment by danclark5** [comment]
That might have done it. I updated to 2.1.2 and it appears to be working. I'll verify Thursday.

Thanks for looking so quickly!

**Comment by danclark5** [comment]
https://github.com/joshleblanc/view_component_reflex/compare/v2.1.1...v2.1.2#diff-f6af1c4d87b1c6223d672959526b2debR5

![Isee what you did there](https://media.giphy.com/media/12ZDIx1Mw1cXVm/giphy.gif)

**Comment by danclark5** [comment]
It works. Thanks!
