### ISSUE TITLE
no _dump_data is defined for class Proc

### ISSUE THREAD

**Issue by cj** [joshleblanc/view_component_reflex#41]
Hi,

I am using v3.4 - I saw the example https://view-component-reflex-expo.grep.sh/data_table where you are doing `accessor: ->(model) { model.gpa.round(2) },`, but I was under the impression ruby caching does not handle proc's or anonymous classes, but your example is working.  When I tried doing something similar locally I get `no _dump_data is defined for class Proc.`  I was wondering what I was missing.

Cheers!

**Comment by cj** [comment]
These are the versions I am using:

`rails 6.1 `
`gem 'stimulus_reflex', '~> 3.4.0.pre9'`
`stimulus": "^2.0.0`
`stimulus_reflex": "3.4.0-pre8`
`gem 'view_component_reflex', '~> 3.0.0'`
`gem 'view_component', '~> 2.23.1'`

**Comment by joshleblanc** [comment]
You'll want to use the memory adapter if you're trying to store procs in state. 

```
ViewComponentReflex::Engine.configure do |config|
  config.state_adapter = ViewComponentReflex::StateAdapter::Memory
end
```

**Comment by cj** [comment]
@joshleblanc ah, I knew I was missing something.  Thank you!
