### ISSUE TITLE
My component tests fail with redis adapter

### ISSUE THREAD

**Issue by drnic** [joshleblanc/view_component_reflex#45]
Some fixes came in for memory adapter https://github.com/joshleblanc/view_component_reflex/commit/67a9bee7e3bdd81a33dba99c774bb336f19c6756, and I think we need similar fix for redis adapter

Some discussion on discord before/after https://discord.com/channels/629472241427415060/725845575278264340/794698716647784458

![image](https://user-images.githubusercontent.com/108/103588227-754ff480-4f34-11eb-919f-dec935a69b74.png)

**Comment by joshleblanc** [comment]
This is fixed in 3.0.5

Sorry for the delay.
