### ISSUE TITLE
around_reflex callback does not work

### ISSUE THREAD

**Issue by pelletencate** [joshleblanc/view_component_reflex#50]
```ruby
class MyComponent < ViewComponentReflex::Component
  around_reflex :do_awesome_stuff

  private

  def do_awesome_stuff
    my_awesome_stuff { yield }
  end
end
```

Expected:

Calls `do_awesome_stuff` with a block that when yielded, executes any reflex.

Observed:

1. Crashes on the method being private while called from outside. This is non-rails compliant, I think the reflex's `method_missing` should use `send` to call it.
2. When I make it public, it is called, but without a block, which also seems to be "discarded" inside the reflex's `method_missing` method.

**Comment by joshleblanc** [comment]
This has been resolved 3.1.4
