### ISSUE TITLE
Sometimes reflexes do not update the ViewComponent

### ISSUE THREAD

**Issue by RolandStuder** [joshleblanc/view_component_reflex#51]
So we noticed that sometimes the VCR does not actually update.

I recorded the behavior here
https://www.loom.com/share/c02c0f069e7d49298caa6c605a3d832e

I think this is a race condition. In the console of the browser we see, that there are two incoming websocket transmissions, one correct one with the morph operation, and one with a nothing-morph.

If the nothing morph arrives first, then the actual morph is not performed.

I assume this is a race condition of some sorts, that may exist because you are not broadcasting this together. Not sure if the the `:nothing morph` should be broadcast at all.

**Comment by joshleblanc** [comment]
This is the most detailed bug report I have ever received 👍

**Comment by joshleblanc** [comment]
3.6.1 should fix this

**Comment by RolandStuder** [comment]
As far as I can tell, this fixed it! @joshleblanc Thanks a lot for this super fast fix!

Happy to hear you liked the detail of the bug report, when I was thinking: Damn, I really should spin up a MVCE :-)
