### ISSUE TITLE
viewcomponent 2.26 looks to break VCR

### ISSUE THREAD

**Issue by drnic** [joshleblanc/view_component_reflex#52]
After upgrading to VC 2.26.0 I started seeing errors like:

```
NameError: undefined local variable or method `collection_parameter' for MessageComponent:Class
    app/components/discussion_component.html.erb:9:in `block in call'
    app/components/discussion_component.html.erb:1:in `call'
    (eval):3:in `render_template_for'
    test/components/discussion_component_test.rb:37:in `block (2 levels) in <class:DiscussionComponentTest>'
```

A quick look shows this is popping up within a VCR component that invokes `SomeOtherComponent.with_collection` into a pure VC/non-VCR component. E.g. `discussion_component.html.erb:9` looks like:

```
<%= render(MessageComponent.with_collection(@messages)) %>
```

**Comment by joshleblanc** [comment]
`with_collection` appears to be broken in generation vc 2.26.

**Comment by joshleblanc** [comment]
https://github.com/github/view_component/issues/642

**Comment by drnic** [comment]
Ha, sorry for assuming they'd broken VCR rather than assuming they had a self regression. I did check their issues first.

**Comment by drnic** [comment]
VC v2.26.1 includes fix
