### ISSUE TITLE
StimulusReflex::Channel Failed to invoke CounterComponent#increment

### ISSUE THREAD

**Issue by danclark5** [joshleblanc/view_component_reflex#7]
I'm trying to integrate view_component_reflex 2.1.4, but I'm getting the following error.

```
StimulusReflex::Channel Failed to invoke CounterComponent#increment! http://localhost:3000/meals/2 uninitialized constant StimulusReflex::NothingBroadcaster /home/dan/.rbenv/versions/2.5.8/lib/ruby/gems/2.5.0/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/active_support.rb:80:in `block in load_missing_constant'
```
If I downgrade to 2.1.2 things work, but I haven't dug too much into this one. I added the [counter_component to establish a working baseline](https://github.com/danclark5/dindin/blob/add-ingredient-search/app/components/counter_component.rb). It's accessible on the [show meal page](https://github.com/danclark5/dindin/blob/add-ingredient-search/app/views/meals/show.html.erb#L7).

Let me know if you have any ideas. I'll continue to dig tomorrow morning.

**Comment by joshleblanc** [comment]
Update stimulus reflex to 3.3.0-pre2. Don't forget to update the npm package too.

**Comment by joshleblanc** [comment]
I pushed 2.1.5 which pins SR to 3.3.0.pre2

**Comment by danclark5** [comment]
That was it. Thanks!
