### ISSUE TITLE
Error: no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by omarluq** [joshleblanc/view_component_reflex#85]
Rails: 7.0.4
Ruby: 3.1.2
stimulus_reflex:  3.5.0.pre9
view_component_reflex:  3.2.0.pre2
view_component:  2.75.0
stimulus-rails: 1.1.1

when I run rails server im getting the following:

```
rails aborted!
lib/view_component/base.rb:509:in `quote': no implicit conversion of nil into String (TypeError) 
from lib/view_component-2.75.0/lib/view_component/base.rb:509:in `inherited'
from lib/view_component_reflex/component.rb:2
```

**Comment by julianrubisch** [comment]
I can confirm this is an issue after VC 2.74.1

**Comment by omarluq** [comment]
@julianrubisch its seems that the root of the error is going back to view components base class.

**Comment by omarluq** [comment]
@julianrubisch  any plans to fix this anytime soon? if i were to push a fix are you open to accepting it and publishing it ?

**Comment by julianrubisch** [comment]
Sorry, you’ll have to ask @joshleblanc

**Comment by omarluq** [comment]
@joshleblanc ^?

**Comment by tunacasserole** [comment]
This issue is preventing me from starting the rails server.  Is this a dead gem?

**Comment by omarluq** [comment]
@julianrubisch do you think that this gem is gonna be deprecated ? is there a way to get in touch with @joshleblanc and see if he is open for giving up the gem for adoption if he plans to not maintain it ?

**Comment by joshleblanc** [comment]
Hello!

Sorry, I wasn't getting these notifications. Let me take a look at this.

**Comment by omarluq** [comment]
@joshleblanc  https://github.com/joshleblanc/view_component_reflex/issues/88 found a temp soltion and the reason behind the error.
