### ISSUE TITLE
Fix for error: no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by omarluq** [joshleblanc/view_component_reflex#88]
Thought I would post this easy fix that  works for now, if you are using VCR with VC version 2.40.1 and up you will get the following when you try to serve the app 

```
rails aborted!
lib/view_component/base.rb:509:in `quote': no implicit conversion of nil into String (TypeError) 
from lib/view_component-2.75.0/lib/view_component/base.rb:509:in `inherited'
from lib/view_component_reflex/component.rb:2
```
To fix this you can do the following: 

In your gem file 
``` ruby
gem 'view_component_reflex', require: false
```

In application_component.rb
``` ruby
require 'view_component_reflex'

class ApplicationComponent < ViewComponentReflex::Component
  # your code goes here 
end
```

Now you can enjoy the VCR goodness with the latest VC release 😈

The reason this error is happening is due to a VC update that happened about 2 months ago where they moved loading the config options to Engine load instead of Application initialization. So not requiring VCR on application initialization fixes this.

**Comment by joshleblanc** [comment]
@omarluq Version 3.2.0 has been released, which fixes this issue.

**Comment by omarluq** [comment]
@joshleblanc you are AWESOME!! love what you are doing with this gem man taking rails to the next level!
